name: Create secret
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    steps:
    - run: gh secret set IMAGE_NAME --body "suriyancss/azure-test/testimage:latest"
      
        
 
        

    
