name: Create secret
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - run: gh secret set IMAGE_NAME --body "suriyancss/azure-test/testimage:latest"
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
    - name: gh secret list
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      run: |
        echo $GH_TOKEN >> test.txt
        echo $IMAGE_NAME >> test.txt
        cat test.txt
        
 
        

    
