name: Container Image CI
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: gh secret set IMAGE_NAME --body "suriyancss/azure-test/testimage:latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
      
    
