name: Create secret
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: gh secret set IMAGE_NAME --body "suriyancss/azure-test/testimage:latest"
        env: 
          repository: SuriyanCSS/azure-test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
