name: Create secret
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - run: gh secret set IMAGE_NAME --body "suriyancss/azure-test/testimage:latest"
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
        
 
        

    
