name: Create secret
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY : https://github.com/SuriyanCSS/azure-test.git
        
    steps:
    - run: |
        cd .git
        gh secret set IMAGE_NAME --body "suriyancss/azure-test/testimage:latest"
      
        
 
        

    
