name: Container Image CI
on: 
  push:
    branches:
      - "master"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: 'suriyancss'
          password: 'welcome@123'

      - name: Build the Container Image
        run: docker build . --file Dockerfile --tag localbuild/testimage:${{ github.sha }}
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        id: docker-image-scan
        with:
          image-ref: 'localbuild/testimage:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          output: 'prod-trivy-results.html'
          #(options = 'LOW,CRITICAL,HIGH,CRITICAL')
          severity: 'LOW' 

      - name: Upload report to Azure Storage Container
        if: failure()
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: DefaultEndpointsProtocol=https;AccountName=st4devops4eus;AccountKey=xr6EnxFB1jQ+Z5FEfDy3frI6N79URs/J9EwOZQ/pKpCbLhzMIqE2RjCngn4HlnBYrxztAh+4qCJO+ASt2tlM1A==;EndpointSuffix=core.windows.net
          container_name: fileuploadtest-suriyan #(input container name)
          source_folder: prod-trivy-results.html
          destination_folder: scanresultappname/scanresultsregistry #(input folder)
          delete_if_exists: true

      - name: Upload Trivy scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'prod-trivy-results.sarif'

      - name: Push Docker Image to AC R
        if: ${{ success() }}
        run: |
          docker tag  localbuild/testimage:${{ github.sha }}  suriyancss/azure-test/testimage:latest
          docker push suriyancss/azure-test/testimage:latest
